//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace Fusioness.FusionessWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MainServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MainService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidarLogonUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoSomethingOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertBicicletaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregarContatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback QualificarRotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregarRotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregarTipoRotasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MainService() {
            this.Url = global::Fusioness.Properties.Settings.Default.Fusioness_FusionessWS_MainService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidarLogonUsuarioCompletedEventHandler ValidarLogonUsuarioCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event DoSomethingCompletedEventHandler DoSomethingCompleted;
        
        /// <remarks/>
        public event InsertBicicletaCompletedEventHandler InsertBicicletaCompleted;
        
        /// <remarks/>
        public event InsertUsuarioCompletedEventHandler InsertUsuarioCompleted;
        
        /// <remarks/>
        public event UpdateUsuarioCompletedEventHandler UpdateUsuarioCompleted;
        
        /// <remarks/>
        public event CarregarContatosCompletedEventHandler CarregarContatosCompleted;
        
        /// <remarks/>
        public event QualificarRotaCompletedEventHandler QualificarRotaCompleted;
        
        /// <remarks/>
        public event GetRotasCompletedEventHandler GetRotasCompleted;
        
        /// <remarks/>
        public event CarregarRotasCompletedEventHandler CarregarRotasCompleted;
        
        /// <remarks/>
        public event CarregarTipoRotasCompletedEventHandler CarregarTipoRotasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarLogonUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidarLogonUsuario(string usuarioSerializado) {
            object[] results = this.Invoke("ValidarLogonUsuario", new object[] {
                        usuarioSerializado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarLogonUsuarioAsync(string usuarioSerializado) {
            this.ValidarLogonUsuarioAsync(usuarioSerializado, null);
        }
        
        /// <remarks/>
        public void ValidarLogonUsuarioAsync(string usuarioSerializado, object userState) {
            if ((this.ValidarLogonUsuarioOperationCompleted == null)) {
                this.ValidarLogonUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarLogonUsuarioOperationCompleted);
            }
            this.InvokeAsync("ValidarLogonUsuario", new object[] {
                        usuarioSerializado}, this.ValidarLogonUsuarioOperationCompleted, userState);
        }
        
        private void OnValidarLogonUsuarioOperationCompleted(object arg) {
            if ((this.ValidarLogonUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarLogonUsuarioCompleted(this, new ValidarLogonUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoSomething", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DoSomething(string nomeDoUsuario) {
            object[] results = this.Invoke("DoSomething", new object[] {
                        nomeDoUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DoSomethingAsync(string nomeDoUsuario) {
            this.DoSomethingAsync(nomeDoUsuario, null);
        }
        
        /// <remarks/>
        public void DoSomethingAsync(string nomeDoUsuario, object userState) {
            if ((this.DoSomethingOperationCompleted == null)) {
                this.DoSomethingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoSomethingOperationCompleted);
            }
            this.InvokeAsync("DoSomething", new object[] {
                        nomeDoUsuario}, this.DoSomethingOperationCompleted, userState);
        }
        
        private void OnDoSomethingOperationCompleted(object arg) {
            if ((this.DoSomethingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoSomethingCompleted(this, new DoSomethingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertBicicleta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertBicicleta(string bicicletaSerializado) {
            object[] results = this.Invoke("InsertBicicleta", new object[] {
                        bicicletaSerializado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertBicicletaAsync(string bicicletaSerializado) {
            this.InsertBicicletaAsync(bicicletaSerializado, null);
        }
        
        /// <remarks/>
        public void InsertBicicletaAsync(string bicicletaSerializado, object userState) {
            if ((this.InsertBicicletaOperationCompleted == null)) {
                this.InsertBicicletaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertBicicletaOperationCompleted);
            }
            this.InvokeAsync("InsertBicicleta", new object[] {
                        bicicletaSerializado}, this.InsertBicicletaOperationCompleted, userState);
        }
        
        private void OnInsertBicicletaOperationCompleted(object arg) {
            if ((this.InsertBicicletaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertBicicletaCompleted(this, new InsertBicicletaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertUsuario(string usuarioSerializado) {
            object[] results = this.Invoke("InsertUsuario", new object[] {
                        usuarioSerializado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertUsuarioAsync(string usuarioSerializado) {
            this.InsertUsuarioAsync(usuarioSerializado, null);
        }
        
        /// <remarks/>
        public void InsertUsuarioAsync(string usuarioSerializado, object userState) {
            if ((this.InsertUsuarioOperationCompleted == null)) {
                this.InsertUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUsuarioOperationCompleted);
            }
            this.InvokeAsync("InsertUsuario", new object[] {
                        usuarioSerializado}, this.InsertUsuarioOperationCompleted, userState);
        }
        
        private void OnInsertUsuarioOperationCompleted(object arg) {
            if ((this.InsertUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertUsuarioCompleted(this, new InsertUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateUsuario(string usuarioSerializado) {
            object[] results = this.Invoke("UpdateUsuario", new object[] {
                        usuarioSerializado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUsuarioAsync(string usuarioSerializado) {
            this.UpdateUsuarioAsync(usuarioSerializado, null);
        }
        
        /// <remarks/>
        public void UpdateUsuarioAsync(string usuarioSerializado, object userState) {
            if ((this.UpdateUsuarioOperationCompleted == null)) {
                this.UpdateUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUsuarioOperationCompleted);
            }
            this.InvokeAsync("UpdateUsuario", new object[] {
                        usuarioSerializado}, this.UpdateUsuarioOperationCompleted, userState);
        }
        
        private void OnUpdateUsuarioOperationCompleted(object arg) {
            if ((this.UpdateUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUsuarioCompleted(this, new UpdateUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CarregarContatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CarregarContatos(int idUsuario) {
            object[] results = this.Invoke("CarregarContatos", new object[] {
                        idUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CarregarContatosAsync(int idUsuario) {
            this.CarregarContatosAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void CarregarContatosAsync(int idUsuario, object userState) {
            if ((this.CarregarContatosOperationCompleted == null)) {
                this.CarregarContatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregarContatosOperationCompleted);
            }
            this.InvokeAsync("CarregarContatos", new object[] {
                        idUsuario}, this.CarregarContatosOperationCompleted, userState);
        }
        
        private void OnCarregarContatosOperationCompleted(object arg) {
            if ((this.CarregarContatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregarContatosCompleted(this, new CarregarContatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QualificarRota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QualificarRota(string rotaSerializada) {
            object[] results = this.Invoke("QualificarRota", new object[] {
                        rotaSerializada});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QualificarRotaAsync(string rotaSerializada) {
            this.QualificarRotaAsync(rotaSerializada, null);
        }
        
        /// <remarks/>
        public void QualificarRotaAsync(string rotaSerializada, object userState) {
            if ((this.QualificarRotaOperationCompleted == null)) {
                this.QualificarRotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQualificarRotaOperationCompleted);
            }
            this.InvokeAsync("QualificarRota", new object[] {
                        rotaSerializada}, this.QualificarRotaOperationCompleted, userState);
        }
        
        private void OnQualificarRotaOperationCompleted(object arg) {
            if ((this.QualificarRotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QualificarRotaCompleted(this, new QualificarRotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRotas(int IdUsuario) {
            object[] results = this.Invoke("GetRotas", new object[] {
                        IdUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRotasAsync(int IdUsuario) {
            this.GetRotasAsync(IdUsuario, null);
        }
        
        /// <remarks/>
        public void GetRotasAsync(int IdUsuario, object userState) {
            if ((this.GetRotasOperationCompleted == null)) {
                this.GetRotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRotasOperationCompleted);
            }
            this.InvokeAsync("GetRotas", new object[] {
                        IdUsuario}, this.GetRotasOperationCompleted, userState);
        }
        
        private void OnGetRotasOperationCompleted(object arg) {
            if ((this.GetRotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRotasCompleted(this, new GetRotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CarregarRotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CarregarRotas() {
            object[] results = this.Invoke("CarregarRotas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CarregarRotasAsync() {
            this.CarregarRotasAsync(null);
        }
        
        /// <remarks/>
        public void CarregarRotasAsync(object userState) {
            if ((this.CarregarRotasOperationCompleted == null)) {
                this.CarregarRotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregarRotasOperationCompleted);
            }
            this.InvokeAsync("CarregarRotas", new object[0], this.CarregarRotasOperationCompleted, userState);
        }
        
        private void OnCarregarRotasOperationCompleted(object arg) {
            if ((this.CarregarRotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregarRotasCompleted(this, new CarregarRotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CarregarTipoRotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CarregarTipoRotas() {
            object[] results = this.Invoke("CarregarTipoRotas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CarregarTipoRotasAsync() {
            this.CarregarTipoRotasAsync(null);
        }
        
        /// <remarks/>
        public void CarregarTipoRotasAsync(object userState) {
            if ((this.CarregarTipoRotasOperationCompleted == null)) {
                this.CarregarTipoRotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregarTipoRotasOperationCompleted);
            }
            this.InvokeAsync("CarregarTipoRotas", new object[0], this.CarregarTipoRotasOperationCompleted, userState);
        }
        
        private void OnCarregarTipoRotasOperationCompleted(object arg) {
            if ((this.CarregarTipoRotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregarTipoRotasCompleted(this, new CarregarTipoRotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ValidarLogonUsuarioCompletedEventHandler(object sender, ValidarLogonUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarLogonUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarLogonUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DoSomethingCompletedEventHandler(object sender, DoSomethingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoSomethingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoSomethingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertBicicletaCompletedEventHandler(object sender, InsertBicicletaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertBicicletaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertBicicletaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertUsuarioCompletedEventHandler(object sender, InsertUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateUsuarioCompletedEventHandler(object sender, UpdateUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CarregarContatosCompletedEventHandler(object sender, CarregarContatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregarContatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregarContatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QualificarRotaCompletedEventHandler(object sender, QualificarRotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QualificarRotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QualificarRotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetRotasCompletedEventHandler(object sender, GetRotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CarregarRotasCompletedEventHandler(object sender, CarregarRotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregarRotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregarRotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CarregarTipoRotasCompletedEventHandler(object sender, CarregarTipoRotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregarTipoRotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregarTipoRotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591