//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18213.
// 
#pragma warning disable 1591

namespace Fusioness.FusionessWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MainServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    public partial class MainService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarLogonUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirBicicletaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarContatosPorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarRotasPorUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirRotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarRotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverRotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterRotaPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarRotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTiposRotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTiposPistaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEventosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterEventoPorIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MainService() {
            this.Url = global::Fusioness.Properties.Settings.Default.Fusioness_FusionessWS_MainService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ValidarLogonUsuarioCompletedEventHandler ValidarLogonUsuarioCompleted;
        
        /// <remarks/>
        public event InserirBicicletaCompletedEventHandler InserirBicicletaCompleted;
        
        /// <remarks/>
        public event InserirUsuarioCompletedEventHandler InserirUsuarioCompleted;
        
        /// <remarks/>
        public event AlterarUsuarioCompletedEventHandler AlterarUsuarioCompleted;
        
        /// <remarks/>
        public event ListarContatosPorUsuarioCompletedEventHandler ListarContatosPorUsuarioCompleted;
        
        /// <remarks/>
        public event ListarRotasPorUsuarioCompletedEventHandler ListarRotasPorUsuarioCompleted;
        
        /// <remarks/>
        public event InserirRotaCompletedEventHandler InserirRotaCompleted;
        
        /// <remarks/>
        public event AlterarRotaCompletedEventHandler AlterarRotaCompleted;
        
        /// <remarks/>
        public event RemoverRotaCompletedEventHandler RemoverRotaCompleted;
        
        /// <remarks/>
        public event ObterRotaPorIdCompletedEventHandler ObterRotaPorIdCompleted;
        
        /// <remarks/>
        public event ListarRotasCompletedEventHandler ListarRotasCompleted;
        
        /// <remarks/>
        public event ListarTiposRotaCompletedEventHandler ListarTiposRotaCompleted;
        
        /// <remarks/>
        public event ListarTiposPistaCompletedEventHandler ListarTiposPistaCompleted;
        
        /// <remarks/>
        public event ListarEventosCompletedEventHandler ListarEventosCompleted;
        
        /// <remarks/>
        public event ObterEventoPorIdCompletedEventHandler ObterEventoPorIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarLogonUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario ValidarLogonUsuario(Usuario usuario) {
            object[] results = this.Invoke("ValidarLogonUsuario", new object[] {
                        usuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarLogonUsuarioAsync(Usuario usuario) {
            this.ValidarLogonUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ValidarLogonUsuarioAsync(Usuario usuario, object userState) {
            if ((this.ValidarLogonUsuarioOperationCompleted == null)) {
                this.ValidarLogonUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarLogonUsuarioOperationCompleted);
            }
            this.InvokeAsync("ValidarLogonUsuario", new object[] {
                        usuario}, this.ValidarLogonUsuarioOperationCompleted, userState);
        }
        
        private void OnValidarLogonUsuarioOperationCompleted(object arg) {
            if ((this.ValidarLogonUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarLogonUsuarioCompleted(this, new ValidarLogonUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InserirBicicleta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Bicicleta InserirBicicleta(Bicicleta bicicleta) {
            object[] results = this.Invoke("InserirBicicleta", new object[] {
                        bicicleta});
            return ((Bicicleta)(results[0]));
        }
        
        /// <remarks/>
        public void InserirBicicletaAsync(Bicicleta bicicleta) {
            this.InserirBicicletaAsync(bicicleta, null);
        }
        
        /// <remarks/>
        public void InserirBicicletaAsync(Bicicleta bicicleta, object userState) {
            if ((this.InserirBicicletaOperationCompleted == null)) {
                this.InserirBicicletaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirBicicletaOperationCompleted);
            }
            this.InvokeAsync("InserirBicicleta", new object[] {
                        bicicleta}, this.InserirBicicletaOperationCompleted, userState);
        }
        
        private void OnInserirBicicletaOperationCompleted(object arg) {
            if ((this.InserirBicicletaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirBicicletaCompleted(this, new InserirBicicletaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InserirUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario InserirUsuario(Usuario usuario) {
            object[] results = this.Invoke("InserirUsuario", new object[] {
                        usuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void InserirUsuarioAsync(Usuario usuario) {
            this.InserirUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void InserirUsuarioAsync(Usuario usuario, object userState) {
            if ((this.InserirUsuarioOperationCompleted == null)) {
                this.InserirUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirUsuarioOperationCompleted);
            }
            this.InvokeAsync("InserirUsuario", new object[] {
                        usuario}, this.InserirUsuarioOperationCompleted, userState);
        }
        
        private void OnInserirUsuarioOperationCompleted(object arg) {
            if ((this.InserirUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirUsuarioCompleted(this, new InserirUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario AlterarUsuario(Usuario usuario) {
            object[] results = this.Invoke("AlterarUsuario", new object[] {
                        usuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario usuario) {
            this.AlterarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario usuario, object userState) {
            if ((this.AlterarUsuarioOperationCompleted == null)) {
                this.AlterarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AlterarUsuario", new object[] {
                        usuario}, this.AlterarUsuarioOperationCompleted, userState);
        }
        
        private void OnAlterarUsuarioOperationCompleted(object arg) {
            if ((this.AlterarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarUsuarioCompleted(this, new AlterarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarContatosPorUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario[] ListarContatosPorUsuario(Usuario usuario) {
            object[] results = this.Invoke("ListarContatosPorUsuario", new object[] {
                        usuario});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarContatosPorUsuarioAsync(Usuario usuario) {
            this.ListarContatosPorUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ListarContatosPorUsuarioAsync(Usuario usuario, object userState) {
            if ((this.ListarContatosPorUsuarioOperationCompleted == null)) {
                this.ListarContatosPorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarContatosPorUsuarioOperationCompleted);
            }
            this.InvokeAsync("ListarContatosPorUsuario", new object[] {
                        usuario}, this.ListarContatosPorUsuarioOperationCompleted, userState);
        }
        
        private void OnListarContatosPorUsuarioOperationCompleted(object arg) {
            if ((this.ListarContatosPorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarContatosPorUsuarioCompleted(this, new ListarContatosPorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarRotasPorUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota[] ListarRotasPorUsuario(Usuario usuario) {
            object[] results = this.Invoke("ListarRotasPorUsuario", new object[] {
                        usuario});
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarRotasPorUsuarioAsync(Usuario usuario) {
            this.ListarRotasPorUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ListarRotasPorUsuarioAsync(Usuario usuario, object userState) {
            if ((this.ListarRotasPorUsuarioOperationCompleted == null)) {
                this.ListarRotasPorUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarRotasPorUsuarioOperationCompleted);
            }
            this.InvokeAsync("ListarRotasPorUsuario", new object[] {
                        usuario}, this.ListarRotasPorUsuarioOperationCompleted, userState);
        }
        
        private void OnListarRotasPorUsuarioOperationCompleted(object arg) {
            if ((this.ListarRotasPorUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarRotasPorUsuarioCompleted(this, new ListarRotasPorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InserirRota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota InserirRota(Rota rota) {
            object[] results = this.Invoke("InserirRota", new object[] {
                        rota});
            return ((Rota)(results[0]));
        }
        
        /// <remarks/>
        public void InserirRotaAsync(Rota rota) {
            this.InserirRotaAsync(rota, null);
        }
        
        /// <remarks/>
        public void InserirRotaAsync(Rota rota, object userState) {
            if ((this.InserirRotaOperationCompleted == null)) {
                this.InserirRotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirRotaOperationCompleted);
            }
            this.InvokeAsync("InserirRota", new object[] {
                        rota}, this.InserirRotaOperationCompleted, userState);
        }
        
        private void OnInserirRotaOperationCompleted(object arg) {
            if ((this.InserirRotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirRotaCompleted(this, new InserirRotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarRota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota AlterarRota(Rota rota) {
            object[] results = this.Invoke("AlterarRota", new object[] {
                        rota});
            return ((Rota)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarRotaAsync(Rota rota) {
            this.AlterarRotaAsync(rota, null);
        }
        
        /// <remarks/>
        public void AlterarRotaAsync(Rota rota, object userState) {
            if ((this.AlterarRotaOperationCompleted == null)) {
                this.AlterarRotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarRotaOperationCompleted);
            }
            this.InvokeAsync("AlterarRota", new object[] {
                        rota}, this.AlterarRotaOperationCompleted, userState);
        }
        
        private void OnAlterarRotaOperationCompleted(object arg) {
            if ((this.AlterarRotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarRotaCompleted(this, new AlterarRotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoverRota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverRota(Rota rota) {
            this.Invoke("RemoverRota", new object[] {
                        rota});
        }
        
        /// <remarks/>
        public void RemoverRotaAsync(Rota rota) {
            this.RemoverRotaAsync(rota, null);
        }
        
        /// <remarks/>
        public void RemoverRotaAsync(Rota rota, object userState) {
            if ((this.RemoverRotaOperationCompleted == null)) {
                this.RemoverRotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverRotaOperationCompleted);
            }
            this.InvokeAsync("RemoverRota", new object[] {
                        rota}, this.RemoverRotaOperationCompleted, userState);
        }
        
        private void OnRemoverRotaOperationCompleted(object arg) {
            if ((this.RemoverRotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverRotaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterRotaPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota ObterRotaPorId(Rota rota) {
            object[] results = this.Invoke("ObterRotaPorId", new object[] {
                        rota});
            return ((Rota)(results[0]));
        }
        
        /// <remarks/>
        public void ObterRotaPorIdAsync(Rota rota) {
            this.ObterRotaPorIdAsync(rota, null);
        }
        
        /// <remarks/>
        public void ObterRotaPorIdAsync(Rota rota, object userState) {
            if ((this.ObterRotaPorIdOperationCompleted == null)) {
                this.ObterRotaPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterRotaPorIdOperationCompleted);
            }
            this.InvokeAsync("ObterRotaPorId", new object[] {
                        rota}, this.ObterRotaPorIdOperationCompleted, userState);
        }
        
        private void OnObterRotaPorIdOperationCompleted(object arg) {
            if ((this.ObterRotaPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterRotaPorIdCompleted(this, new ObterRotaPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarRotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota[] ListarRotas() {
            object[] results = this.Invoke("ListarRotas", new object[0]);
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarRotasAsync() {
            this.ListarRotasAsync(null);
        }
        
        /// <remarks/>
        public void ListarRotasAsync(object userState) {
            if ((this.ListarRotasOperationCompleted == null)) {
                this.ListarRotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarRotasOperationCompleted);
            }
            this.InvokeAsync("ListarRotas", new object[0], this.ListarRotasOperationCompleted, userState);
        }
        
        private void OnListarRotasOperationCompleted(object arg) {
            if ((this.ListarRotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarRotasCompleted(this, new ListarRotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTiposRota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TipoRota[] ListarTiposRota() {
            object[] results = this.Invoke("ListarTiposRota", new object[0]);
            return ((TipoRota[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTiposRotaAsync() {
            this.ListarTiposRotaAsync(null);
        }
        
        /// <remarks/>
        public void ListarTiposRotaAsync(object userState) {
            if ((this.ListarTiposRotaOperationCompleted == null)) {
                this.ListarTiposRotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTiposRotaOperationCompleted);
            }
            this.InvokeAsync("ListarTiposRota", new object[0], this.ListarTiposRotaOperationCompleted, userState);
        }
        
        private void OnListarTiposRotaOperationCompleted(object arg) {
            if ((this.ListarTiposRotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTiposRotaCompleted(this, new ListarTiposRotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTiposPista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TipoPista[] ListarTiposPista() {
            object[] results = this.Invoke("ListarTiposPista", new object[0]);
            return ((TipoPista[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTiposPistaAsync() {
            this.ListarTiposPistaAsync(null);
        }
        
        /// <remarks/>
        public void ListarTiposPistaAsync(object userState) {
            if ((this.ListarTiposPistaOperationCompleted == null)) {
                this.ListarTiposPistaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTiposPistaOperationCompleted);
            }
            this.InvokeAsync("ListarTiposPista", new object[0], this.ListarTiposPistaOperationCompleted, userState);
        }
        
        private void OnListarTiposPistaOperationCompleted(object arg) {
            if ((this.ListarTiposPistaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTiposPistaCompleted(this, new ListarTiposPistaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarEventos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Evento[] ListarEventos() {
            object[] results = this.Invoke("ListarEventos", new object[0]);
            return ((Evento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarEventosAsync() {
            this.ListarEventosAsync(null);
        }
        
        /// <remarks/>
        public void ListarEventosAsync(object userState) {
            if ((this.ListarEventosOperationCompleted == null)) {
                this.ListarEventosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEventosOperationCompleted);
            }
            this.InvokeAsync("ListarEventos", new object[0], this.ListarEventosOperationCompleted, userState);
        }
        
        private void OnListarEventosOperationCompleted(object arg) {
            if ((this.ListarEventosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEventosCompleted(this, new ListarEventosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterEventoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Evento ObterEventoPorId(Evento evento) {
            object[] results = this.Invoke("ObterEventoPorId", new object[] {
                        evento});
            return ((Evento)(results[0]));
        }
        
        /// <remarks/>
        public void ObterEventoPorIdAsync(Evento evento) {
            this.ObterEventoPorIdAsync(evento, null);
        }
        
        /// <remarks/>
        public void ObterEventoPorIdAsync(Evento evento, object userState) {
            if ((this.ObterEventoPorIdOperationCompleted == null)) {
                this.ObterEventoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterEventoPorIdOperationCompleted);
            }
            this.InvokeAsync("ObterEventoPorId", new object[] {
                        evento}, this.ObterEventoPorIdOperationCompleted, userState);
        }
        
        private void OnObterEventoPorIdOperationCompleted(object arg) {
            if ((this.ObterEventoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterEventoPorIdCompleted(this, new ObterEventoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : EntityBase {
        
        private int idUsuarioField;
        
        private string nomeField;
        
        private string loginField;
        
        private string senhaField;
        
        private string emailField;
        
        private System.Nullable<int> idadeField;
        
        private string sexoField;
        
        private string urlImagemField;
        
        private Bicicleta[] bicicletasField;
        
        private Contato[] contatosField;
        
        private Contato[] contatos1Field;
        
        private Evento[] eventoesField;
        
        private EventoUsuario[] eventoUsuariosField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Idade {
            get {
                return this.idadeField;
            }
            set {
                this.idadeField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string UrlImagem {
            get {
                return this.urlImagemField;
            }
            set {
                this.urlImagemField = value;
            }
        }
        
        /// <remarks/>
        public Bicicleta[] Bicicletas {
            get {
                return this.bicicletasField;
            }
            set {
                this.bicicletasField = value;
            }
        }
        
        /// <remarks/>
        public Contato[] Contatos {
            get {
                return this.contatosField;
            }
            set {
                this.contatosField = value;
            }
        }
        
        /// <remarks/>
        public Contato[] Contatos1 {
            get {
                return this.contatos1Field;
            }
            set {
                this.contatos1Field = value;
            }
        }
        
        /// <remarks/>
        public Evento[] Eventoes {
            get {
                return this.eventoesField;
            }
            set {
                this.eventoesField = value;
            }
        }
        
        /// <remarks/>
        public EventoUsuario[] EventoUsuarios {
            get {
                return this.eventoUsuariosField;
            }
            set {
                this.eventoUsuariosField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bicicleta : EntityBase {
        
        private int idBicicletaField;
        
        private int idUsuarioField;
        
        private string modeloField;
        
        private string marcaField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int IdBicicleta {
            get {
                return this.idBicicletaField;
            }
            set {
                this.idBicicletaField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resposta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusEvento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventoUsuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoRota))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoPista))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QualidadeRota))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Dificuldade))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoCoordenada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Coordenada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rota))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Evento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConviteEvento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Contato))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bicicleta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Usuario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Resposta : EntityBase {
        
        private int idRespostaField;
        
        private string descricaoField;
        
        private ConviteEvento[] conviteEventosField;
        
        /// <remarks/>
        public int IdResposta {
            get {
                return this.idRespostaField;
            }
            set {
                this.idRespostaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public ConviteEvento[] ConviteEventos {
            get {
                return this.conviteEventosField;
            }
            set {
                this.conviteEventosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConviteEvento : EntityBase {
        
        private int idUsuarioField;
        
        private int idContatoField;
        
        private int idEventoField;
        
        private System.Nullable<int> idRespostaField;
        
        private Contato contatoField;
        
        private Evento eventoField;
        
        private Resposta respostaField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdContato {
            get {
                return this.idContatoField;
            }
            set {
                this.idContatoField = value;
            }
        }
        
        /// <remarks/>
        public int IdEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdResposta {
            get {
                return this.idRespostaField;
            }
            set {
                this.idRespostaField = value;
            }
        }
        
        /// <remarks/>
        public Contato Contato {
            get {
                return this.contatoField;
            }
            set {
                this.contatoField = value;
            }
        }
        
        /// <remarks/>
        public Evento Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
            }
        }
        
        /// <remarks/>
        public Resposta Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Contato : EntityBase {
        
        private int idUsuarioField;
        
        private int idContatoField;
        
        private Usuario usuarioField;
        
        private Usuario usuario1Field;
        
        private ConviteEvento[] conviteEventosField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdContato {
            get {
                return this.idContatoField;
            }
            set {
                this.idContatoField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario1 {
            get {
                return this.usuario1Field;
            }
            set {
                this.usuario1Field = value;
            }
        }
        
        /// <remarks/>
        public ConviteEvento[] ConviteEventos {
            get {
                return this.conviteEventosField;
            }
            set {
                this.conviteEventosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Evento : EntityBase {
        
        private int idEventoField;
        
        private int idUsuarioField;
        
        private int idRotaField;
        
        private string tituloField;
        
        private string descricaoField;
        
        private System.DateTime dataField;
        
        private string urlImagemField;
        
        private bool publicoField;
        
        private ConviteEvento[] conviteEventosField;
        
        private Rota rotaField;
        
        private Usuario usuarioField;
        
        private EventoUsuario[] eventoUsuariosField;
        
        /// <remarks/>
        public int IdEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdRota {
            get {
                return this.idRotaField;
            }
            set {
                this.idRotaField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string UrlImagem {
            get {
                return this.urlImagemField;
            }
            set {
                this.urlImagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Publico {
            get {
                return this.publicoField;
            }
            set {
                this.publicoField = value;
            }
        }
        
        /// <remarks/>
        public ConviteEvento[] ConviteEventos {
            get {
                return this.conviteEventosField;
            }
            set {
                this.conviteEventosField = value;
            }
        }
        
        /// <remarks/>
        public Rota Rota {
            get {
                return this.rotaField;
            }
            set {
                this.rotaField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public EventoUsuario[] EventoUsuarios {
            get {
                return this.eventoUsuariosField;
            }
            set {
                this.eventoUsuariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rota : EntityBase {
        
        private int idRotaField;
        
        private int idUsuarioField;
        
        private System.Nullable<int> idTipoPistaField;
        
        private int idTipoRotaField;
        
        private System.Nullable<int> idDificuldadeField;
        
        private System.Nullable<int> idQualidadeRotaField;
        
        private Coordenada[] coordenadasField;
        
        private Dificuldade dificuldadeField;
        
        private Evento[] eventosField;
        
        private QualidadeRota qualidadeRotaField;
        
        private TipoPista tipoPistaField;
        
        private TipoRota tipoRotaField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int IdRota {
            get {
                return this.idRotaField;
            }
            set {
                this.idRotaField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdTipoPista {
            get {
                return this.idTipoPistaField;
            }
            set {
                this.idTipoPistaField = value;
            }
        }
        
        /// <remarks/>
        public int IdTipoRota {
            get {
                return this.idTipoRotaField;
            }
            set {
                this.idTipoRotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdDificuldade {
            get {
                return this.idDificuldadeField;
            }
            set {
                this.idDificuldadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdQualidadeRota {
            get {
                return this.idQualidadeRotaField;
            }
            set {
                this.idQualidadeRotaField = value;
            }
        }
        
        /// <remarks/>
        public Coordenada[] Coordenadas {
            get {
                return this.coordenadasField;
            }
            set {
                this.coordenadasField = value;
            }
        }
        
        /// <remarks/>
        public Dificuldade Dificuldade {
            get {
                return this.dificuldadeField;
            }
            set {
                this.dificuldadeField = value;
            }
        }
        
        /// <remarks/>
        public Evento[] Eventos {
            get {
                return this.eventosField;
            }
            set {
                this.eventosField = value;
            }
        }
        
        /// <remarks/>
        public QualidadeRota QualidadeRota {
            get {
                return this.qualidadeRotaField;
            }
            set {
                this.qualidadeRotaField = value;
            }
        }
        
        /// <remarks/>
        public TipoPista TipoPista {
            get {
                return this.tipoPistaField;
            }
            set {
                this.tipoPistaField = value;
            }
        }
        
        /// <remarks/>
        public TipoRota TipoRota {
            get {
                return this.tipoRotaField;
            }
            set {
                this.tipoRotaField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Coordenada : EntityBase {
        
        private int idCoordenadaField;
        
        private int idRotaField;
        
        private System.Nullable<int> idTipoCoordenadaField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private System.Nullable<System.DateTime> dataField;
        
        private Rota rotaField;
        
        private TipoCoordenada tipoCoordenadaField;
        
        /// <remarks/>
        public int IdCoordenada {
            get {
                return this.idCoordenadaField;
            }
            set {
                this.idCoordenadaField = value;
            }
        }
        
        /// <remarks/>
        public int IdRota {
            get {
                return this.idRotaField;
            }
            set {
                this.idRotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdTipoCoordenada {
            get {
                return this.idTipoCoordenadaField;
            }
            set {
                this.idTipoCoordenadaField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Rota Rota {
            get {
                return this.rotaField;
            }
            set {
                this.rotaField = value;
            }
        }
        
        /// <remarks/>
        public TipoCoordenada TipoCoordenada {
            get {
                return this.tipoCoordenadaField;
            }
            set {
                this.tipoCoordenadaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoCoordenada : EntityBase {
        
        private int idTipoCoordenadaField;
        
        private string descricaoField;
        
        private Coordenada[] coordenadasField;
        
        /// <remarks/>
        public int IdTipoCoordenada {
            get {
                return this.idTipoCoordenadaField;
            }
            set {
                this.idTipoCoordenadaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Coordenada[] Coordenadas {
            get {
                return this.coordenadasField;
            }
            set {
                this.coordenadasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Dificuldade : EntityBase {
        
        private int idDificuldadeField;
        
        private string descricaoField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdDificuldade {
            get {
                return this.idDificuldadeField;
            }
            set {
                this.idDificuldadeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QualidadeRota : EntityBase {
        
        private int idQualidadeRotaField;
        
        private string descricaoField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdQualidadeRota {
            get {
                return this.idQualidadeRotaField;
            }
            set {
                this.idQualidadeRotaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoPista : EntityBase {
        
        private int idTipoPistaField;
        
        private string descricaoField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdTipoPista {
            get {
                return this.idTipoPistaField;
            }
            set {
                this.idTipoPistaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoRota : EntityBase {
        
        private int idTipoRotaField;
        
        private string descricaoField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdTipoRota {
            get {
                return this.idTipoRotaField;
            }
            set {
                this.idTipoRotaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EventoUsuario : EntityBase {
        
        private int idUsuarioField;
        
        private int idEventoField;
        
        private System.Nullable<int> idStatusEventoField;
        
        private string statusDescricaoField;
        
        private Evento eventoField;
        
        private StatusEvento statusEventoField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdStatusEvento {
            get {
                return this.idStatusEventoField;
            }
            set {
                this.idStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescricao {
            get {
                return this.statusDescricaoField;
            }
            set {
                this.statusDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public Evento Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
            }
        }
        
        /// <remarks/>
        public StatusEvento StatusEvento {
            get {
                return this.statusEventoField;
            }
            set {
                this.statusEventoField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusEvento : EntityBase {
        
        private int idStatusEventoField;
        
        private string descricaoField;
        
        private EventoUsuario[] eventoUsuariosField;
        
        /// <remarks/>
        public int IdStatusEvento {
            get {
                return this.idStatusEventoField;
            }
            set {
                this.idStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public EventoUsuario[] EventoUsuarios {
            get {
                return this.eventoUsuariosField;
            }
            set {
                this.eventoUsuariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ValidarLogonUsuarioCompletedEventHandler(object sender, ValidarLogonUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarLogonUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarLogonUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InserirBicicletaCompletedEventHandler(object sender, InserirBicicletaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InserirBicicletaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InserirBicicletaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Bicicleta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Bicicleta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InserirUsuarioCompletedEventHandler(object sender, InserirUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InserirUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InserirUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void AlterarUsuarioCompletedEventHandler(object sender, AlterarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ListarContatosPorUsuarioCompletedEventHandler(object sender, ListarContatosPorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarContatosPorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarContatosPorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ListarRotasPorUsuarioCompletedEventHandler(object sender, ListarRotasPorUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarRotasPorUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarRotasPorUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rota[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void InserirRotaCompletedEventHandler(object sender, InserirRotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InserirRotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InserirRotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rota)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void AlterarRotaCompletedEventHandler(object sender, AlterarRotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarRotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarRotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rota)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void RemoverRotaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ObterRotaPorIdCompletedEventHandler(object sender, ObterRotaPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterRotaPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterRotaPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rota)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ListarRotasCompletedEventHandler(object sender, ListarRotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarRotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarRotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rota[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ListarTiposRotaCompletedEventHandler(object sender, ListarTiposRotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTiposRotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTiposRotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoRota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoRota[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ListarTiposPistaCompletedEventHandler(object sender, ListarTiposPistaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTiposPistaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTiposPistaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoPista[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoPista[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ListarEventosCompletedEventHandler(object sender, ListarEventosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEventosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEventosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Evento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Evento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ObterEventoPorIdCompletedEventHandler(object sender, ObterEventoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterEventoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterEventoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Evento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Evento)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591