//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace Fusioness.FusionessWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MainServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    public partial class MainService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoSomethingOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarLogonUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertBicicletaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregarContatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback QualificarRotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregarRotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregarTipoRotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregarEventosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterEventoPorIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MainService() {
            this.Url = global::Fusioness.Properties.Settings.Default.Fusioness_FusionessWS_MainService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event DoSomethingCompletedEventHandler DoSomethingCompleted;
        
        /// <remarks/>
        public event ValidarLogonUsuarioCompletedEventHandler ValidarLogonUsuarioCompleted;
        
        /// <remarks/>
        public event InsertBicicletaCompletedEventHandler InsertBicicletaCompleted;
        
        /// <remarks/>
        public event InsertUsuarioCompletedEventHandler InsertUsuarioCompleted;
        
        /// <remarks/>
        public event UpdateUsuarioCompletedEventHandler UpdateUsuarioCompleted;
        
        /// <remarks/>
        public event CarregarContatosCompletedEventHandler CarregarContatosCompleted;
        
        /// <remarks/>
        public event QualificarRotaCompletedEventHandler QualificarRotaCompleted;
        
        /// <remarks/>
        public event GetRotasCompletedEventHandler GetRotasCompleted;
        
        /// <remarks/>
        public event CarregarRotasCompletedEventHandler CarregarRotasCompleted;
        
        /// <remarks/>
        public event CarregarTipoRotasCompletedEventHandler CarregarTipoRotasCompleted;
        
        /// <remarks/>
        public event CarregarEventosCompletedEventHandler CarregarEventosCompleted;
        
        /// <remarks/>
        public event ObterEventoPorIdCompletedEventHandler ObterEventoPorIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoSomething", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario DoSomething(Usuario usuario) {
            object[] results = this.Invoke("DoSomething", new object[] {
                        usuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void DoSomethingAsync(Usuario usuario) {
            this.DoSomethingAsync(usuario, null);
        }
        
        /// <remarks/>
        public void DoSomethingAsync(Usuario usuario, object userState) {
            if ((this.DoSomethingOperationCompleted == null)) {
                this.DoSomethingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoSomethingOperationCompleted);
            }
            this.InvokeAsync("DoSomething", new object[] {
                        usuario}, this.DoSomethingOperationCompleted, userState);
        }
        
        private void OnDoSomethingOperationCompleted(object arg) {
            if ((this.DoSomethingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoSomethingCompleted(this, new DoSomethingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarLogonUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario ValidarLogonUsuario(Usuario usuario) {
            object[] results = this.Invoke("ValidarLogonUsuario", new object[] {
                        usuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarLogonUsuarioAsync(Usuario usuario) {
            this.ValidarLogonUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ValidarLogonUsuarioAsync(Usuario usuario, object userState) {
            if ((this.ValidarLogonUsuarioOperationCompleted == null)) {
                this.ValidarLogonUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarLogonUsuarioOperationCompleted);
            }
            this.InvokeAsync("ValidarLogonUsuario", new object[] {
                        usuario}, this.ValidarLogonUsuarioOperationCompleted, userState);
        }
        
        private void OnValidarLogonUsuarioOperationCompleted(object arg) {
            if ((this.ValidarLogonUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarLogonUsuarioCompleted(this, new ValidarLogonUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertBicicleta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Bicicleta InsertBicicleta(Bicicleta bicicleta) {
            object[] results = this.Invoke("InsertBicicleta", new object[] {
                        bicicleta});
            return ((Bicicleta)(results[0]));
        }
        
        /// <remarks/>
        public void InsertBicicletaAsync(Bicicleta bicicleta) {
            this.InsertBicicletaAsync(bicicleta, null);
        }
        
        /// <remarks/>
        public void InsertBicicletaAsync(Bicicleta bicicleta, object userState) {
            if ((this.InsertBicicletaOperationCompleted == null)) {
                this.InsertBicicletaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertBicicletaOperationCompleted);
            }
            this.InvokeAsync("InsertBicicleta", new object[] {
                        bicicleta}, this.InsertBicicletaOperationCompleted, userState);
        }
        
        private void OnInsertBicicletaOperationCompleted(object arg) {
            if ((this.InsertBicicletaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertBicicletaCompleted(this, new InsertBicicletaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario InsertUsuario(Usuario usuario) {
            object[] results = this.Invoke("InsertUsuario", new object[] {
                        usuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void InsertUsuarioAsync(Usuario usuario) {
            this.InsertUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void InsertUsuarioAsync(Usuario usuario, object userState) {
            if ((this.InsertUsuarioOperationCompleted == null)) {
                this.InsertUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUsuarioOperationCompleted);
            }
            this.InvokeAsync("InsertUsuario", new object[] {
                        usuario}, this.InsertUsuarioOperationCompleted, userState);
        }
        
        private void OnInsertUsuarioOperationCompleted(object arg) {
            if ((this.InsertUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertUsuarioCompleted(this, new InsertUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario UpdateUsuario(Usuario usuario) {
            object[] results = this.Invoke("UpdateUsuario", new object[] {
                        usuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUsuarioAsync(Usuario usuario) {
            this.UpdateUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void UpdateUsuarioAsync(Usuario usuario, object userState) {
            if ((this.UpdateUsuarioOperationCompleted == null)) {
                this.UpdateUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUsuarioOperationCompleted);
            }
            this.InvokeAsync("UpdateUsuario", new object[] {
                        usuario}, this.UpdateUsuarioOperationCompleted, userState);
        }
        
        private void OnUpdateUsuarioOperationCompleted(object arg) {
            if ((this.UpdateUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUsuarioCompleted(this, new UpdateUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CarregarContatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario[] CarregarContatos(int idUsuario) {
            object[] results = this.Invoke("CarregarContatos", new object[] {
                        idUsuario});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void CarregarContatosAsync(int idUsuario) {
            this.CarregarContatosAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void CarregarContatosAsync(int idUsuario, object userState) {
            if ((this.CarregarContatosOperationCompleted == null)) {
                this.CarregarContatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregarContatosOperationCompleted);
            }
            this.InvokeAsync("CarregarContatos", new object[] {
                        idUsuario}, this.CarregarContatosOperationCompleted, userState);
        }
        
        private void OnCarregarContatosOperationCompleted(object arg) {
            if ((this.CarregarContatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregarContatosCompleted(this, new CarregarContatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QualificarRota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota QualificarRota(Rota rota) {
            object[] results = this.Invoke("QualificarRota", new object[] {
                        rota});
            return ((Rota)(results[0]));
        }
        
        /// <remarks/>
        public void QualificarRotaAsync(Rota rota) {
            this.QualificarRotaAsync(rota, null);
        }
        
        /// <remarks/>
        public void QualificarRotaAsync(Rota rota, object userState) {
            if ((this.QualificarRotaOperationCompleted == null)) {
                this.QualificarRotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQualificarRotaOperationCompleted);
            }
            this.InvokeAsync("QualificarRota", new object[] {
                        rota}, this.QualificarRotaOperationCompleted, userState);
        }
        
        private void OnQualificarRotaOperationCompleted(object arg) {
            if ((this.QualificarRotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QualificarRotaCompleted(this, new QualificarRotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota[] GetRotas(int IdUsuario) {
            object[] results = this.Invoke("GetRotas", new object[] {
                        IdUsuario});
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRotasAsync(int IdUsuario) {
            this.GetRotasAsync(IdUsuario, null);
        }
        
        /// <remarks/>
        public void GetRotasAsync(int IdUsuario, object userState) {
            if ((this.GetRotasOperationCompleted == null)) {
                this.GetRotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRotasOperationCompleted);
            }
            this.InvokeAsync("GetRotas", new object[] {
                        IdUsuario}, this.GetRotasOperationCompleted, userState);
        }
        
        private void OnGetRotasOperationCompleted(object arg) {
            if ((this.GetRotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRotasCompleted(this, new GetRotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CarregarRotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota[] CarregarRotas() {
            object[] results = this.Invoke("CarregarRotas", new object[0]);
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        public void CarregarRotasAsync() {
            this.CarregarRotasAsync(null);
        }
        
        /// <remarks/>
        public void CarregarRotasAsync(object userState) {
            if ((this.CarregarRotasOperationCompleted == null)) {
                this.CarregarRotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregarRotasOperationCompleted);
            }
            this.InvokeAsync("CarregarRotas", new object[0], this.CarregarRotasOperationCompleted, userState);
        }
        
        private void OnCarregarRotasOperationCompleted(object arg) {
            if ((this.CarregarRotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregarRotasCompleted(this, new CarregarRotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CarregarTipoRotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TipoRota[] CarregarTipoRotas() {
            object[] results = this.Invoke("CarregarTipoRotas", new object[0]);
            return ((TipoRota[])(results[0]));
        }
        
        /// <remarks/>
        public void CarregarTipoRotasAsync() {
            this.CarregarTipoRotasAsync(null);
        }
        
        /// <remarks/>
        public void CarregarTipoRotasAsync(object userState) {
            if ((this.CarregarTipoRotasOperationCompleted == null)) {
                this.CarregarTipoRotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregarTipoRotasOperationCompleted);
            }
            this.InvokeAsync("CarregarTipoRotas", new object[0], this.CarregarTipoRotasOperationCompleted, userState);
        }
        
        private void OnCarregarTipoRotasOperationCompleted(object arg) {
            if ((this.CarregarTipoRotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregarTipoRotasCompleted(this, new CarregarTipoRotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CarregarEventos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Evento[] CarregarEventos() {
            object[] results = this.Invoke("CarregarEventos", new object[0]);
            return ((Evento[])(results[0]));
        }
        
        /// <remarks/>
        public void CarregarEventosAsync() {
            this.CarregarEventosAsync(null);
        }
        
        /// <remarks/>
        public void CarregarEventosAsync(object userState) {
            if ((this.CarregarEventosOperationCompleted == null)) {
                this.CarregarEventosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregarEventosOperationCompleted);
            }
            this.InvokeAsync("CarregarEventos", new object[0], this.CarregarEventosOperationCompleted, userState);
        }
        
        private void OnCarregarEventosOperationCompleted(object arg) {
            if ((this.CarregarEventosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregarEventosCompleted(this, new CarregarEventosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterEventoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Evento ObterEventoPorId(int id) {
            object[] results = this.Invoke("ObterEventoPorId", new object[] {
                        id});
            return ((Evento)(results[0]));
        }
        
        /// <remarks/>
        public void ObterEventoPorIdAsync(int id) {
            this.ObterEventoPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void ObterEventoPorIdAsync(int id, object userState) {
            if ((this.ObterEventoPorIdOperationCompleted == null)) {
                this.ObterEventoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterEventoPorIdOperationCompleted);
            }
            this.InvokeAsync("ObterEventoPorId", new object[] {
                        id}, this.ObterEventoPorIdOperationCompleted, userState);
        }
        
        private void OnObterEventoPorIdOperationCompleted(object arg) {
            if ((this.ObterEventoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterEventoPorIdCompleted(this, new ObterEventoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : EntityBase {
        
        private int idUsuarioField;
        
        private string nomeField;
        
        private string loginField;
        
        private string senhaField;
        
        private string emailField;
        
        private System.Nullable<int> idadeField;
        
        private string sexoField;
        
        private string urlImagemField;
        
        private Bicicleta[] bicicletasField;
        
        private Contato[] contatosField;
        
        private Contato[] contatos1Field;
        
        private Evento[] eventoesField;
        
        private EventoUsuario[] eventoUsuariosField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Idade {
            get {
                return this.idadeField;
            }
            set {
                this.idadeField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string UrlImagem {
            get {
                return this.urlImagemField;
            }
            set {
                this.urlImagemField = value;
            }
        }
        
        /// <remarks/>
        public Bicicleta[] Bicicletas {
            get {
                return this.bicicletasField;
            }
            set {
                this.bicicletasField = value;
            }
        }
        
        /// <remarks/>
        public Contato[] Contatos {
            get {
                return this.contatosField;
            }
            set {
                this.contatosField = value;
            }
        }
        
        /// <remarks/>
        public Contato[] Contatos1 {
            get {
                return this.contatos1Field;
            }
            set {
                this.contatos1Field = value;
            }
        }
        
        /// <remarks/>
        public Evento[] Eventoes {
            get {
                return this.eventoesField;
            }
            set {
                this.eventoesField = value;
            }
        }
        
        /// <remarks/>
        public EventoUsuario[] EventoUsuarios {
            get {
                return this.eventoUsuariosField;
            }
            set {
                this.eventoUsuariosField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bicicleta : EntityBase {
        
        private int idBicicletaField;
        
        private int idUsuarioField;
        
        private string modeloField;
        
        private string marcaField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int IdBicicleta {
            get {
                return this.idBicicletaField;
            }
            set {
                this.idBicicletaField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resposta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusEvento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventoUsuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoRota))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoPista))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QualidadeRota))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Dificuldade))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoCoordenada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Coordenada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rota))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Evento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConviteEvento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Contato))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bicicleta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Usuario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Resposta : EntityBase {
        
        private int idRespostaField;
        
        private string descricaoField;
        
        private ConviteEvento[] conviteEventosField;
        
        /// <remarks/>
        public int IdResposta {
            get {
                return this.idRespostaField;
            }
            set {
                this.idRespostaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public ConviteEvento[] ConviteEventos {
            get {
                return this.conviteEventosField;
            }
            set {
                this.conviteEventosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConviteEvento : EntityBase {
        
        private int idUsuarioField;
        
        private int idContatoField;
        
        private int idEventoField;
        
        private System.Nullable<int> idRespostaField;
        
        private Contato contatoField;
        
        private Evento eventoField;
        
        private Resposta respostaField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdContato {
            get {
                return this.idContatoField;
            }
            set {
                this.idContatoField = value;
            }
        }
        
        /// <remarks/>
        public int IdEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdResposta {
            get {
                return this.idRespostaField;
            }
            set {
                this.idRespostaField = value;
            }
        }
        
        /// <remarks/>
        public Contato Contato {
            get {
                return this.contatoField;
            }
            set {
                this.contatoField = value;
            }
        }
        
        /// <remarks/>
        public Evento Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
            }
        }
        
        /// <remarks/>
        public Resposta Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Contato : EntityBase {
        
        private int idUsuarioField;
        
        private int idContatoField;
        
        private Usuario usuarioField;
        
        private Usuario usuario1Field;
        
        private ConviteEvento[] conviteEventosField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdContato {
            get {
                return this.idContatoField;
            }
            set {
                this.idContatoField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario1 {
            get {
                return this.usuario1Field;
            }
            set {
                this.usuario1Field = value;
            }
        }
        
        /// <remarks/>
        public ConviteEvento[] ConviteEventos {
            get {
                return this.conviteEventosField;
            }
            set {
                this.conviteEventosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Evento : EntityBase {
        
        private int idEventoField;
        
        private int idUsuarioField;
        
        private int idRotaField;
        
        private string tituloField;
        
        private string descricaoField;
        
        private System.DateTime dataField;
        
        private string urlImagemField;
        
        private bool publicoField;
        
        private ConviteEvento[] conviteEventosField;
        
        private Rota rotaField;
        
        private Usuario usuarioField;
        
        private EventoUsuario[] eventoUsuariosField;
        
        /// <remarks/>
        public int IdEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdRota {
            get {
                return this.idRotaField;
            }
            set {
                this.idRotaField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string UrlImagem {
            get {
                return this.urlImagemField;
            }
            set {
                this.urlImagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Publico {
            get {
                return this.publicoField;
            }
            set {
                this.publicoField = value;
            }
        }
        
        /// <remarks/>
        public ConviteEvento[] ConviteEventos {
            get {
                return this.conviteEventosField;
            }
            set {
                this.conviteEventosField = value;
            }
        }
        
        /// <remarks/>
        public Rota Rota {
            get {
                return this.rotaField;
            }
            set {
                this.rotaField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public EventoUsuario[] EventoUsuarios {
            get {
                return this.eventoUsuariosField;
            }
            set {
                this.eventoUsuariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rota : EntityBase {
        
        private int idRotaField;
        
        private int idUsuarioField;
        
        private System.Nullable<int> idTipoPistaField;
        
        private int idTipoRotaField;
        
        private System.Nullable<int> idDificuldadeField;
        
        private System.Nullable<int> idQualidadeRotaField;
        
        private Coordenada[] coordenadasField;
        
        private Dificuldade dificuldadeField;
        
        private Evento[] eventosField;
        
        private QualidadeRota qualidadeRotaField;
        
        private TipoPista tipoPistaField;
        
        private TipoRota tipoRotaField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int IdRota {
            get {
                return this.idRotaField;
            }
            set {
                this.idRotaField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdTipoPista {
            get {
                return this.idTipoPistaField;
            }
            set {
                this.idTipoPistaField = value;
            }
        }
        
        /// <remarks/>
        public int IdTipoRota {
            get {
                return this.idTipoRotaField;
            }
            set {
                this.idTipoRotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdDificuldade {
            get {
                return this.idDificuldadeField;
            }
            set {
                this.idDificuldadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdQualidadeRota {
            get {
                return this.idQualidadeRotaField;
            }
            set {
                this.idQualidadeRotaField = value;
            }
        }
        
        /// <remarks/>
        public Coordenada[] Coordenadas {
            get {
                return this.coordenadasField;
            }
            set {
                this.coordenadasField = value;
            }
        }
        
        /// <remarks/>
        public Dificuldade Dificuldade {
            get {
                return this.dificuldadeField;
            }
            set {
                this.dificuldadeField = value;
            }
        }
        
        /// <remarks/>
        public Evento[] Eventos {
            get {
                return this.eventosField;
            }
            set {
                this.eventosField = value;
            }
        }
        
        /// <remarks/>
        public QualidadeRota QualidadeRota {
            get {
                return this.qualidadeRotaField;
            }
            set {
                this.qualidadeRotaField = value;
            }
        }
        
        /// <remarks/>
        public TipoPista TipoPista {
            get {
                return this.tipoPistaField;
            }
            set {
                this.tipoPistaField = value;
            }
        }
        
        /// <remarks/>
        public TipoRota TipoRota {
            get {
                return this.tipoRotaField;
            }
            set {
                this.tipoRotaField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Coordenada : EntityBase {
        
        private int idCoordenadaField;
        
        private int idRotaField;
        
        private System.Nullable<int> idTipoCoordenadaField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private System.Nullable<System.DateTime> dataField;
        
        private Rota rotaField;
        
        private TipoCoordenada tipoCoordenadaField;
        
        /// <remarks/>
        public int IdCoordenada {
            get {
                return this.idCoordenadaField;
            }
            set {
                this.idCoordenadaField = value;
            }
        }
        
        /// <remarks/>
        public int IdRota {
            get {
                return this.idRotaField;
            }
            set {
                this.idRotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdTipoCoordenada {
            get {
                return this.idTipoCoordenadaField;
            }
            set {
                this.idTipoCoordenadaField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Rota Rota {
            get {
                return this.rotaField;
            }
            set {
                this.rotaField = value;
            }
        }
        
        /// <remarks/>
        public TipoCoordenada TipoCoordenada {
            get {
                return this.tipoCoordenadaField;
            }
            set {
                this.tipoCoordenadaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoCoordenada : EntityBase {
        
        private int idTipoCoordenadaField;
        
        private string descricaoField;
        
        private Coordenada[] coordenadasField;
        
        /// <remarks/>
        public int IdTipoCoordenada {
            get {
                return this.idTipoCoordenadaField;
            }
            set {
                this.idTipoCoordenadaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Coordenada[] Coordenadas {
            get {
                return this.coordenadasField;
            }
            set {
                this.coordenadasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Dificuldade : EntityBase {
        
        private int idDificuldadeField;
        
        private string descricaoField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdDificuldade {
            get {
                return this.idDificuldadeField;
            }
            set {
                this.idDificuldadeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QualidadeRota : EntityBase {
        
        private int idQualidadeRotaField;
        
        private string descricaoField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdQualidadeRota {
            get {
                return this.idQualidadeRotaField;
            }
            set {
                this.idQualidadeRotaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoPista : EntityBase {
        
        private int idTipoPistaField;
        
        private string descricaoField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdTipoPista {
            get {
                return this.idTipoPistaField;
            }
            set {
                this.idTipoPistaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoRota : EntityBase {
        
        private int idTipoRotaField;
        
        private string descricaoField;
        
        private Rota[] rotasField;
        
        /// <remarks/>
        public int IdTipoRota {
            get {
                return this.idTipoRotaField;
            }
            set {
                this.idTipoRotaField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public Rota[] Rotas {
            get {
                return this.rotasField;
            }
            set {
                this.rotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EventoUsuario : EntityBase {
        
        private int idUsuarioField;
        
        private int idEventoField;
        
        private System.Nullable<int> idStatusEventoField;
        
        private string statusDescricaoField;
        
        private Evento eventoField;
        
        private StatusEvento statusEventoField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdStatusEvento {
            get {
                return this.idStatusEventoField;
            }
            set {
                this.idStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescricao {
            get {
                return this.statusDescricaoField;
            }
            set {
                this.statusDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public Evento Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
            }
        }
        
        /// <remarks/>
        public StatusEvento StatusEvento {
            get {
                return this.statusEventoField;
            }
            set {
                this.statusEventoField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StatusEvento : EntityBase {
        
        private int idStatusEventoField;
        
        private string descricaoField;
        
        private EventoUsuario[] eventoUsuariosField;
        
        /// <remarks/>
        public int IdStatusEvento {
            get {
                return this.idStatusEventoField;
            }
            set {
                this.idStatusEventoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public EventoUsuario[] EventoUsuarios {
            get {
                return this.eventoUsuariosField;
            }
            set {
                this.eventoUsuariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DoSomethingCompletedEventHandler(object sender, DoSomethingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoSomethingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoSomethingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ValidarLogonUsuarioCompletedEventHandler(object sender, ValidarLogonUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarLogonUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarLogonUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertBicicletaCompletedEventHandler(object sender, InsertBicicletaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertBicicletaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertBicicletaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Bicicleta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Bicicleta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertUsuarioCompletedEventHandler(object sender, InsertUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateUsuarioCompletedEventHandler(object sender, UpdateUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CarregarContatosCompletedEventHandler(object sender, CarregarContatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregarContatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregarContatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QualificarRotaCompletedEventHandler(object sender, QualificarRotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QualificarRotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QualificarRotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rota Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rota)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetRotasCompletedEventHandler(object sender, GetRotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rota[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CarregarRotasCompletedEventHandler(object sender, CarregarRotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregarRotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregarRotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rota[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CarregarTipoRotasCompletedEventHandler(object sender, CarregarTipoRotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregarTipoRotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregarTipoRotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoRota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoRota[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CarregarEventosCompletedEventHandler(object sender, CarregarEventosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregarEventosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregarEventosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Evento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Evento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ObterEventoPorIdCompletedEventHandler(object sender, ObterEventoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterEventoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterEventoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Evento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Evento)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591