//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusioness.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
#if DEBUG
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Fusioness.Services/MainService.asmx")]
#else
        [global::System.Configuration.DefaultSettingValueAttribute("http://fusionessapi.apphb.com/Fusioness.Services/MainService.asmx")]
#endif
        public string Fusioness_FusionessWS_MainService
        {
            get
            {
#if DEBUG
                return ((string)(this["Fusioness_FusionessWS_MainService_Debug"]));
#else
                return ((string)(this["Fusioness_FusionessWS_MainService_Release"]));
#endif

            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Fusioness.Services/MainService.asmx")]
        public string Fusioness_FusionessWS_MainService_Debug
        {
            get
            {
                return ((string)(this["Fusioness_FusionessWS_MainService_Debug"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fusionessapi.apphb.com/Fusioness.Services/MainService.asmx")]
        public string Fusioness_FusionessWS_MainService_Release
        {
            get
            {
                return ((string)(this["Fusioness_FusionessWS_MainService_Release"]));
            }
        }
    }
}